label: 'Novos utilizadores'
description: 'Mostra uma lista de contas de utilizador mais recentes no sítio.'
display:
  default:
    display_title: Predefinido
    display_options:
      title: 'Novos utilizadores'
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          sort_asc_label: Asc
          sort_desc_label: Desc
  block_1:
    display_title: 'Novos utilizadores'
    display_options:
      display_description: 'Uma lista de utilizadores novos'
      block_description: 'Novos utilizadores'
      block_category: Utilizador
