label: 'Items promovidos'
display:
  default:
    display_title: Predefinido
    display_options:
      fields:
        title:
          separator: ', '
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          sort_asc_label: Asc
          sort_desc_label: Desc
