_core:
  default_config_hash: LBaNHR2iSQWenwxlXmCU37WJ_f9sEOC6XocWNx_9JOU
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: en
    es: es
    pt-pt: pt-pt
  domains:
    en: ''
    es: ''
    pt-pt: ''
selected_langcode: site_default
